### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by ymoreiratiti** [vip-git/universal-json-schema#472] opened 2022-07-08 13:36 UTC
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

-----

```json
{
  "dependencies": {
    "@emotion/cache": "^11.9.3",
    "@emotion/react": "^11.9.3",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.9.3",
    "@fontsource/roboto": "^4.5.7",
    "@mui/icons-material": "^5.8.4",
    "@mui/material": "^5.8.6",
    "axios": "^0.27.2",
    "is-ci": "^3.0.1",
    "lodash": "^4.17.21",
    "next": "12.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-jsonschema-form-material-ui": "3.0.0-rc.7",
    "swr": "^1.3.0"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.182",
    "@types/node": "18.0.0",
    "@types/react": "18.0.14",
    "@types/react-dom": "18.0.5",
    "@typescript-eslint/eslint-plugin": "^5.30.0",
    "eslint": "8.18.0",
    "eslint-config-next": "12.2.0",
    "eslint-config-prettier": "^8.5.0",
    "husky": "^8.0.1",
    "prettier": "^2.7.1",
    "sleep-promise": "^9.1.0",
    "typescript": "4.7.4"
  }
}
```

-----

```jsx
import { useState } from 'react';
import MaterialJsonSchemaForm from 'react-jsonschema-form-material-ui';

const givenSchema = {
  "title": "A single-field form",
  "type": "string"
}
const givenFormData = "initial value"

export function ComponentTestForm() {
  const [formData, setFormData] = useState(givenFormData)
  return (
    <MaterialJsonSchemaForm
      schema={givenSchema}
      formData={formData}
    />
  );
}
```

**Comment by vip-git** [comment] 2022-07-08 17:46
Hi @ymoreiratiti - closing this as it's a duplicate of https://github.com/vip-git/universal-json-schema/issues/465 .

If you follow the comment from Alex you would find that there is extra setup needed with webpack to have this working.

Thanks - V

**Closed** 2022-07-08 17:47 UTC
